### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by timomitchel** [ChesleyRGravel/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [] I named my directories correctly. 
`We were looking for your class and object files to be contained within a **classes** directory.`
- [x] I named my files correctly.
- [] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [x] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
- [x] I pushed my changes to Github.

`We'd like to see this file formatted similar to the way we did it in classes five with indentation and numbering similar to something like this. Take a look at this [example](https://gist.github.com/timomitchel/e8a76b8479f89d8749079f3577fa7b69) for reference.`

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [ ] I structured and named my directories and files correctly.
- [ ] The four attributes I chose for **Class #1** represent properties or characteristics.
- [ ] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [ ] The four methods I chose for **Class #1** represent behaviors or actions.
- [ ] I described what the methods do in **Class 1**, including which attributes they use or modify.
- [] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 
`No class file present`

Class #1 Example Object Checklist
- [ ] The object I chose for **Class 1** is an instance of this class.
`It looks like you were making an instance of a desk class, but that class file is not present in the repo
- [x] I listed the values for each attribute of this object. 
- [ ] I listed the results of each method for this object.
`For the methods we are looking for clear actions/behaviors. These are best represented by verbs. For example **raise**, **lower**, or **roll** would all be solid methods on this teacher class. The first two would modify the height attribute. And the last one could modify an attribute called is_in_motion by changing it from false to true. It's hard to tell where the name of your method ends and the description begins.`
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 
`Your methods did not modify any attributes, and we would like this file to be formatted in a way that is more readable than this. A new line for each attribute and method would be a great way to accomplish this`

Class #2 Checklist
- [x] The four attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [x] The four methods I chose for **Class #2** represent behaviors or actions.
- [x] I described what the methods do in **Class 2**, including which attributes they use or modify.
- [x] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

`This file looks good, but remember to pick one naming convention and stick with it, while also describing how you modify an attribute with each method. It also needs to be formatted in a way that is more readable as described above.`

Class #2 Example Object Checklist
- [ ] The object I chose for **Class 2** is an instance of this class. 
- [ ] I listed the values for each attribute of this object. 
- [ ] I listed the results of each method for this object. 
- [ ] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 

### Assessment Results
- [ ] Technical Ready
- [ ] Pending
- [ ] Not Technical Ready
